### ISSUE TITLE
Interesting things we should evaluate in the Praktikum 

### ISSUE THREAD

**Issue by rauldds** [rauldds/Hyperspectral_CT_Recon#35]
- It'll be interesting to see how deep the NN should be (test different depths)
- Check different patch sizes, different number of neighbors (play around with the receptive field)
- Maybe eliminate skipped connections and evaluate

**Comment by luisdavid64** [comment]
Follow-up:
- How are the classes different by exploring spectrograms? What channels matter for certain materials?
- How can we compress data and is it useful?
- What is the best receptive field for this task? Local or global features better?
     1. Depth of network
     2. Size of convolutions
     3. Full image vs patches
     4. Extreme case 1D Network vs 2D vs 3D
- Ablation studies: Single CT vs Dual CT vs Hyperspectral

**Comment by luisdavid64** [comment]
Possible Tasks:
 1) Explore 1D model. Can we predict material per pixel (1x1 convs on Hyperspectral
 2) Explore compression techniques. Apply PCA, blending of Hyperspectral data so that we pass the best information to network.
 3) Explore receptive field of network. Tasks here would be to explore which patch size is better and which network depth is better. This gives us an idea whether local or global features are better for the task of material segmentation.
 4) Manually explore sinogram visualizations OR collect statistics on which Hyperspectral levels are more important for each material. For example: which channels are more useful to determine H2O vs Nivea Lotion.

**Comment by luisdavid64** [comment]
1-3 where explored and 4 was explored indirectly.
